version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
