[tox]
env_list =
    compatibility
    mocks3
    coverage
    py{310,311,312,313}{,-compatibility,-coverage,-jsonschema}{,-devdeps}{,-parallel}{,-pytestdev}
    asdf{-standard,-transform-schemas,-unit-schemas,-wcs-schemas,-coordinates-schemas,-astropy,-zarr,-compression}
    astrocut
    gwcs
    jwst
    stdatamodels
    stpipe
    roman_datamodels
    weldx
    sunpy
    dkist

[testenv]
set_env =
    devdeps: PIP_EXTRA_INDEX_URL = https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
    devdeps: ASDF_UNSTABLE_CORE_SCHEMAS = 1
deps =
    compatibility: virtualenv
    coverage: pytest-cov
    devdeps: -rrequirements-dev.txt
    numpydev: cython
    oldestdeps: minimum_dependencies
    parallel: pytest-xdist
    pytestdev: git+https://github.com/pytest-dev/pytest
    mocks3: moto[s3,server]
    mocks3: boto
    mocks3: fsspec
    mocks3: s3fs>2023.12.1
extras = all,tests
# astropy will complain if the home directory is missing
pass_env = HOME
package = editable
commands_pre =
    python -m pip install --upgrade pip

# Generate `requiremments-min.txt`
    oldestdeps: minimum_dependencies asdf --filename {env_tmp_dir}/requirements-min.txt
# Force install everything from `requirements-min.txt`
    oldestdeps: pip install -r {env_tmp_dir}/requirements-min.txt

    pip freeze
# print out the default core schemas version
    python -c "import asdf; print(f'Core schemas default version: {asdf.get_config().default_version}')"
commands =
    pytest \
    devdeps: -W "ignore::asdf_standard.exceptions.UnstableCoreSchemasWarning" \
    compatibility: integration_tests/compatibility/ \
    mocks3: integration_tests/mocks3/ \
    --durations=10 \
    jsonschema: --jsonschema \
    parallel: --numprocesses auto \
    coverage: --cov --cov-config pyproject.toml --cov-report term-missing --cov-report xml \
    {posargs}
