name: build

on:
  pull_request:
  release:
    types: [released]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@22ddf09dfabb443adddfb9f861b7d41a787d6b1a # v3.0.3
    with:
      upload_to_pypi: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
      test_extras: tests
      test_command: pytest --pyargs asdf
    secrets:
      pypi_token: ${{ secrets.PYPI_PASSWORD_ASDF_MAINTAINER }}
