name: Scheduled Workflows

on:
  # Allow manual runs through the web UI
  workflow_dispatch:
  schedule:
    #        ┌───────── minute (0 - 59)
    #        │ ┌───────── hour (0 - 23)
    #        │ │ ┌───────── day of the month (1 - 31)
    #        │ │ │ ┌───────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────── day of the week (0 - 6 or SUN-SAT)
    - cron: '0 6 * * 1'  # Every Monday at 6am UTC

  #TMP
  pull_request:

jobs:
  dispatch_workflows:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        branch:
          - master
          - 2.15.x
        workflow:
          - ci.yml
          - downstream.yml
          - s390x.yml

    uses: asdf-format/asdf/.github/workflows/${{ matrix.workflows }}@${{ matrix.branch }}
